/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registrar;

import Clases.ImagenFondo;
import Clases.PilaLibro;
import Interfaces.frmMenu;
import static Registrar.frmRegistrarAlumno.mensajeDeAlerta;
import java.awt.Cursor;


public class frmRegistrarLibro extends javax.swing.JFrame {

    frmMenu principal;
    PilaLibro pilaLibro;
    
    
    String nombre;
    String seccion;
    int paginas;
    float tamaño;
    
    ImagenFondo fondo;
    
    public frmRegistrarLibro(frmMenu menu, PilaLibro datoL) {
        fondo = new ImagenFondo("src/Imagenes/christin-hume-k2Kcwkandwg-unsplash.jpg");
        this.setContentPane(fondo);
        
        initComponents();
        
       
        jbnPop.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbnPush.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbnRegresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        
        this.principal = menu;
        this.pilaLibro = datoL;
        
        
        String nombre = "";
        String seccion = "";
        int paginas = 0;
        float tamaño =0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNombreLibro = new javax.swing.JTextField();
        jtfSeccion = new javax.swing.JTextField();
        jtfPaginas = new javax.swing.JTextField();
        jtfTamaño = new javax.swing.JTextField();
        jbnPush = new javax.swing.JButton();
        jbnPop = new javax.swing.JButton();
        jbnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-user-20-24 (1).png"))); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seccion");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paginas");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tamaño del libro");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registrar Libro");

        jtfNombreLibro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfSeccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfPaginas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfTamaño.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbnPush.setBackground(new java.awt.Color(0, 0, 0));
        jbnPush.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbnPush.setForeground(new java.awt.Color(255, 255, 255));
        jbnPush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-text-28-32.png"))); // NOI18N
        jbnPush.setText("Push");
        jbnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPushActionPerformed(evt);
            }
        });

        jbnPop.setBackground(new java.awt.Color(0, 0, 0));
        jbnPop.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbnPop.setForeground(new java.awt.Color(255, 255, 255));
        jbnPop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-x-mark-4-32.png"))); // NOI18N
        jbnPop.setText("Pop");
        jbnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPopActionPerformed(evt);
            }
        });

        jbnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        jbnRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jbnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-undo-6-32.png"))); // NOI18N
        jbnRegresar.setText("Regresar");
        jbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addComponent(jbnPop))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfNombreLibro)
                        .addComponent(jtfSeccion)
                        .addComponent(jtfPaginas)
                        .addComponent(jtfTamaño, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbnPush)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jbnRegresar)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnPush)
                    .addComponent(jbnPop)
                    .addComponent(jbnRegresar))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPushActionPerformed
        // TODO add your handling code here:
        nombre = jtfNombreLibro.getText();
        seccion = jtfSeccion.getText();
        paginas = Integer.parseInt(jtfPaginas.getText());
        tamaño = Float.parseFloat(jtfTamaño.getText());
        
        pilaLibro.pushLibro(nombre, seccion, paginas, tamaño);
        jtfNombreLibro.setText("");
        jtfSeccion.setText("");
        jtfPaginas.setText("");
        jtfTamaño.setText("");
        jtfNombreLibro.requestFocus();
        
         mensajeDeAlerta("Usuario Registrado" , "Registro" );
    }//GEN-LAST:event_jbnPushActionPerformed

    private void jbnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPopActionPerformed
        // TODO add your handling code here:
        pilaLibro.popLibro();
         mensajeDeAlerta("Usuario Eliminado" , "Eliminado" );
    }//GEN-LAST:event_jbnPopActionPerformed

    private void jbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegresarActionPerformed
        // TODO add your handling code here:
        principal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jbnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmRegistrarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbnPop;
    private javax.swing.JButton jbnPush;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JTextField jtfNombreLibro;
    private javax.swing.JTextField jtfPaginas;
    private javax.swing.JTextField jtfSeccion;
    private javax.swing.JTextField jtfTamaño;
    // End of variables declaration//GEN-END:variables
}
