/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.ImagenFondo;
import Clases.Usuario;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author HECTOR MAURICIO
 */
public class frmIngreso extends javax.swing.JFrame {

       
    //Arreglo de uruarios 
    Usuario[] usuario = new Usuario[5];
    ImagenFondo fondo;
    
    public frmIngreso() {
        
        fondo = new ImagenFondo("src/Imagenes/clarisse-meyer-jKU2NneZAbI-unsplash.jpg");
        this.setContentPane(fondo);
        
        initComponents();

        /*
        ImageIcon imagenIcono = new ImageIcon("src/Imagenes/iconmonstr-book-17-32.png");
        Image imagen = imagenIcono.getImage();
        Image imagenEscalada = imagen.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
        imagenIcono = new ImageIcon(imagenEscalada);
        jlbIcon.setIcon(imagenIcono);*/
        
        
        jbnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbnSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
         //Inicializar arreglo
        usuario[0] = new Usuario("h","1");
        usuario[1] = new Usuario("Carlos","12345");
        usuario[2] = new Usuario("Luis","12345");
        usuario[3] = new Usuario("Alex","12345");
        usuario[4] = new Usuario("Christofer","12345");   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbMensaje = new javax.swing.JLabel();
        jpfContraseña = new javax.swing.JPasswordField();
        jbnAceptar = new javax.swing.JButton();
        jbnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlbIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jtfUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jtfUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jtfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 239, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jlbMensaje.setBackground(new java.awt.Color(255, 255, 255));
        jlbMensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlbMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jlbMensaje.setText("mensaje");
        getContentPane().add(jlbMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jpfContraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jpfContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));
        jpfContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpfContraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 239, -1));

        jbnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbnAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jbnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-check-mark-7-32.png"))); // NOI18N
        jbnAceptar.setText("Aceptar");
        jbnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, -1));

        jbnSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbnSalir.setForeground(new java.awt.Color(0, 0, 0));
        jbnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmonstr-door-6-32.png"))); // NOI18N
        jbnSalir.setText("Salir");
        jbnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar a la Biblioteca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));
        getContentPane().add(jlbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsuarioKeyTyped

        char tam = 12;

        char caracter = evt.getKeyChar();

        if(!Character.isLetter(caracter))
        {
            getToolkit().beep();
            evt.consume();
        }

        if(jtfUsuario.getText().length()>=tam)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfUsuarioKeyTyped

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed

    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jpfContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfContraseñaKeyTyped
        char tam = 5;

        char caracter = evt.getKeyChar();

        if(Character.isLetter(caracter))
        {
            getToolkit().beep();
            evt.consume();
        }

        if(jpfContraseña.getText().length()>=tam)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jpfContraseñaKeyTyped

    private void jbnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbnSalirActionPerformed

    private void jbnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAceptarActionPerformed
        //Obtener los textos de caja de texto y caja de contraseña
        String usr = jtfUsuario.getText();
        String con = jpfContraseña.getText();
        jlbMensaje.setText(jpfContraseña.getPassword().toString()); //para el mensaje si esta mal la contraseña

        //Bandera para determinar si es usuario valido
        boolean valido = false;

        for(int i = 0; i < usuario.length ; i++){
            if(usuario[i].getUsuario().equals(usr) && usuario[i].getContraseña().equals(con))
            {

                //Se pasa como parametros: Usuario y ventana actual
                frmMenu abrir = new frmMenu();
                abrir.setVisible(true); //Muestra la ventana de Formula
                this.setVisible(false);  //Hace invisible la ventana

                valido = true;
            }
        }
        if(!valido)
        {
            jlbMensaje.setText("Cuenta sin acceso");

        }
    }//GEN-LAST:event_jbnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbnAceptar;
    private javax.swing.JButton jbnSalir;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbMensaje;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
